repos:
  - repo: local
    hooks:
      - id: company-agnostic
        name: Source code is free of "duolingo" mentions
        entry: bash -c '! grep -Hin duolingo $@' --
        language: system
        files: ^src/*
  - repo: https://github.com/duolingo/pre-commit-hooks.git
    rev: 1.7.0
    hooks:
      - id: duolingo
        exclude: config.yaml
